const $ = (s, r = document) => r.querySelector(s);
const $$ = (s, r = document) => [...r.querySelectorAll(s)];
const state = { stage: 0, device: 'fluid', activeApp: null, runningApps: new Set(), appHistory: [], notes: [], stockTimer: null, stock: null };

const stocks = [
  { symbol: 'AAPL', name: 'Apple Inc.', price: 214.42 }, { symbol: 'TSLA', name: 'Tesla Motors', price: 286.15 },
  { symbol: 'NVDA', name: 'NVIDIA Corp.', price: 162.88 }, { symbol: 'MSFT', name: 'Microsoft', price: 501.31 },
  { symbol: 'GOOGL', name: 'Alphabet', price: 193.75 }, { symbol: 'AMZN', name: 'Amazon', price: 232.41 },
  { symbol: 'RELIANCE', name: 'Reliance Industries', price: 1429.2 }, { symbol: 'TCS', name: 'Tata Consultancy Services', price: 3892.5 },
  { symbol: 'INFOSYS', name: 'Infosys Ltd.', price: 1584.3 }, { symbol: 'META', name: 'Meta Platforms', price: 611.08 }
];
const apps = {
  stocks: { name: 'Stocks Shower', icon: '📈', render: renderStocks },
  transcoder: { name: 'Any-to-Any Transcoder', icon: '🧬', render: renderTranscoder },
  micro: { name: 'Micro-Control Lab', icon: '🔌', render: renderMicroLab },
  jarvis: { name: 'Jarvis Terminal', icon: '◈', render: renderJarvis }
};

function showStage(n) { $$('.stage').forEach(x => x.classList.remove('active')); $(`#stage${n}`).classList.add('active'); state.stage = n; }
function tickClock() { $('#systemClock').textContent = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }); }
setInterval(tickClock, 1000); tickClock();

function renderLauncher() {
  $('#launcherGrid').innerHTML = Object.entries(apps).map(([key, app]) => `<button class="launcher-tile" data-app="${key}"><span class="launcher-orb">${app.icon}</span><span class="launcher-name">${app.name}</span></button>`).join('');
  $$('.launcher-tile').forEach(btn => btn.addEventListener('click', () => openApp(btn.dataset.app)));
}
function openApp(key) {
  const app = apps[key]; if (!app) return;
  if (state.stockTimer) clearInterval(state.stockTimer);
  state.activeApp = key; state.runningApps.add(key); state.appHistory = [key, ...state.appHistory.filter(x => x !== key)];
  $('#sheetIcon').textContent = app.icon; $('#sheetTitle').textContent = app.name; $('#sheetBody').innerHTML = app.render();
  $('#sheet').classList.add('open'); $('#taskSwitcher').classList.remove('open'); bindApp(key); renderTaskSwitcher();
}
function closeActiveSheet() { if (state.stockTimer) clearInterval(state.stockTimer); $('#sheet').classList.remove('open'); state.activeApp = null; }
function renderTaskSwitcher() {
  const list = state.appHistory.filter(k => state.runningApps.has(k));
  $('#taskSwitcher').innerHTML = list.length ? list.map(k => `<button class="task-card" data-app="${k}"><span class="mini">${apps[k].icon}</span><strong>${apps[k].name}</strong><span class="task-exit" data-exit="${k}">×</span></button>`).join('') : '<p class="muted">No active applications.</p>';
  $$('.task-card').forEach(card => card.addEventListener('click', () => openApp(card.dataset.app)));
  $$('[data-exit]').forEach(btn => btn.addEventListener('click', e => { e.stopPropagation(); terminateApp(btn.dataset.exit); }));
}
function terminateApp(key) { state.runningApps.delete(key); state.appHistory = state.appHistory.filter(k => k !== key); if (state.activeApp === key) closeActiveSheet(); renderTaskSwitcher(); }

function renderStocks() {
  return `<div class="app-grid two-col"><div class="panel stock-search"><label>Search global ticker</label><input id="stockInput" placeholder="AAPL, TSLA, NVDA, RELIANCE..." autocomplete="off"><div id="stockSuggestions" class="suggestions" hidden></div><p class="muted">Select a symbol to start the random-walk live market terminal.</p><div id="stockMeta"></div></div><div class="panel"><p class="eyebrow">Live Price</p><div id="stockPrice" class="price">--</div><small id="stockDelta" class="muted">Awaiting selection</small></div><div class="panel" style="grid-column:1/-1"><svg id="stockChart" class="chart" viewBox="0 0 900 260" preserveAspectRatio="none"><path id="stockPath" d="" fill="none" stroke="#61f4ff" stroke-width="4"/><path id="stockGlow" d="" fill="none" stroke="rgba(97,244,255,.22)" stroke-width="14"/></svg></div></div>`;
}
function bindStocks() { const input = $('#stockInput'), box = $('#stockSuggestions'); input.addEventListener('input', () => { const q = input.value.toUpperCase(); const hits = stocks.filter(s => `${s.symbol} ${s.name}`.toUpperCase().includes(q)).slice(0, 6); box.hidden = !q; box.innerHTML = hits.map(s => `<button data-symbol="${s.symbol}"><strong>${s.symbol}</strong> · ${s.name}</button>`).join(''); $$('[data-symbol]', box).forEach(b => b.onclick = () => selectStock(b.dataset.symbol)); }); selectStock('AAPL'); }
function selectStock(symbol) { const s = stocks.find(x => x.symbol === symbol); if (!s) return; state.stock = { ...s, history: Array.from({ length: 38 }, (_, i) => s.price * (0.94 + Math.random() * .12 + i / 900)) }; $('#stockInput').value = s.symbol; $('#stockSuggestions').hidden = true; $('#stockMeta').innerHTML = `<h3>${s.symbol}</h3><p>${s.name}</p>`; drawStock(); if (state.stockTimer) clearInterval(state.stockTimer); state.stockTimer = setInterval(updateStock, 1000); updateStock(); }
function updateStock() { const s = state.stock; const old = s.price; s.price = Math.max(1, s.price + (Math.random() - .48) * old * .012); s.history.push(s.price); s.history = s.history.slice(-48); const up = s.price >= old; $('#stockPrice').textContent = `$${s.price.toFixed(2)}`; $('#stockPrice').className = `price ${up ? 'up' : 'down'}`; $('#stockDelta').textContent = `${up ? '▲' : '▼'} ${(s.price - old).toFixed(2)} · ${new Date().toLocaleTimeString()}`; drawStock(); }
function drawStock() { const h = state.stock.history, min = Math.min(...h), max = Math.max(...h), span = max - min || 1; const d = h.map((v, i) => `${i ? 'L' : 'M'}${(i / (h.length - 1)) * 900},${240 - ((v - min) / span) * 220}`).join(' '); $('#stockPath').setAttribute('d', d); $('#stockGlow').setAttribute('d', d); }

function renderTranscoder() { return `<div class="app-grid two-col"><div class="panel"><div id="dropZone" class="drop-zone"><h3>Drop or choose a file</h3><input id="fileInput" type="file"><p class="muted">PNG, JPG, WebP, JSON, CSV, Markdown, or mock large-file packages.</p></div><label>Destination format</label><select id="formatSelect"><option value="png">PNG</option><option value="jpeg">JPG</option><option value="webp">WebP</option><option value="csv">CSV</option><option value="json">JSON</option><option value="html">HTML</option><option value="zip">Mock ZIP Bundle</option></select><button id="transcodeBtn" class="primary-action">Transcode Locally</button></div><div class="panel"><h3>Core Processing Simulator</h3><div class="progress"><span id="progressFill"></span></div><pre id="transcodeLog">Ready.</pre></div></div>`; }
function bindTranscoder() { const dz = $('#dropZone'), input = $('#fileInput'); ['dragenter','dragover'].forEach(e => dz.addEventListener(e, ev => { ev.preventDefault(); dz.classList.add('drag'); })); ['drop','dragleave'].forEach(e => dz.addEventListener(e, ev => { ev.preventDefault(); dz.classList.remove('drag'); if (ev.dataTransfer?.files?.[0]) input.files = ev.dataTransfer.files; })); $('#transcodeBtn').onclick = () => transcode(input.files[0], $('#formatSelect').value); }
function download(name, data) { const a = document.createElement('a'); a.href = data; a.download = name; a.click(); }
function transcode(file, fmt) { if (!file) return logTrans('Choose a file first.'); const ext = file.name.split('.').pop().toLowerCase(); if (file.type.startsWith('image/')) { const img = new Image(); img.onload = () => { const c = document.createElement('canvas'); c.width = img.width; c.height = img.height; c.getContext('2d').drawImage(img, 0, 0); download(`wizos-${Date.now()}.${fmt}`, c.toDataURL(`image/${fmt}`, .92)); logTrans(`Canvas exported ${img.width}×${img.height} ${fmt.toUpperCase()} image.`); }; img.src = URL.createObjectURL(file); return; } const reader = new FileReader(); reader.onload = () => processText(file.name, ext, fmt, reader.result); reader.readAsText(file); }
function processText(name, ext, fmt, text) { if (ext === 'json' && fmt === 'csv') { const rows = JSON.parse(text); const keys = Object.keys(Array.isArray(rows) ? rows[0] : rows); const csv = [keys.join(','), ...(Array.isArray(rows) ? rows : [rows]).map(r => keys.map(k => JSON.stringify(r[k] ?? '')).join(','))].join('\n'); download(name.replace(/\.[^.]+$/, '.csv'), 'data:text/csv;charset=utf-8,' + encodeURIComponent(csv)); logTrans('JSON translated to CSV.'); } else if (ext === 'csv' && fmt === 'json') { const [head, ...lines] = text.trim().split(/\r?\n/); const keys = head.split(','); const json = lines.map(l => Object.fromEntries(l.split(',').map((v, i) => [keys[i], v]))); download(name.replace(/\.[^.]+$/, '.json'), 'data:application/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(json, null, 2))); logTrans('CSV translated to JSON.'); } else if ((ext === 'md' || ext === 'markdown') && fmt === 'html') { const html = text.replace(/^### (.*)$/gm, '<h3>$1</h3>').replace(/^## (.*)$/gm, '<h2>$1</h2>').replace(/^# (.*)$/gm, '<h1>$1</h1>').replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>'); download(name.replace(/\.[^.]+$/, '.html'), 'data:text/html;charset=utf-8,' + encodeURIComponent(html)); logTrans('Markdown translated to HTML.'); } else simulateZip(); }
function simulateZip() { let p = 0; const id = setInterval(() => { p += Math.random() * 14; $('#progressFill').style.width = `${Math.min(100, p)}%`; logTrans(`Processing ${(p * 8.4).toFixed(0)}MB · ${(22 + Math.random() * 48).toFixed(1)} MB/s · block ${Math.ceil(p)}`); if (p >= 100) { clearInterval(id); download('wizos-mock-bundle.zip', 'data:application/zip;base64,V2l6T1MgbW9jayB6aXAgYnVuZGxl'); logTrans('Mock ZIP compiled and downloaded.'); } }, 220); }
function logTrans(t) { $('#transcodeLog').textContent = t; }

function renderMicroLab() { return `<div class="app-grid two-col"><div class="panel"><h3>Hardware Blueprint</h3><label>Controller</label><select id="board"><option>Arduino Uno</option><option>ESP32</option></select><div class="hardware-options">${['LED','Potentiometer','Temperature Sensor','Micro Servo Motor'].map(x => `<button class="chip" data-part="${x}">${x}</button>`).join('')}</div><pre id="wiring"></pre><h3>Ohm\'s Law Diagnostic Core</h3><label>Voltage</label><input id="voltage" type="range" min="1" max="12" step="0.1" value="5"><label>Resistor Ω</label><input id="resistor" type="range" min="100" max="1000" step="10" value="220"><p id="ohm"></p></div><div class="panel"><h3>Live Code Compilation</h3><button id="copyCode" class="copy-btn">Copy Code</button><pre id="codeOut"></pre></div></div>`; }
function bindMicro() { $$('.chip').forEach(c => c.onclick = () => { c.classList.toggle('active'); compileMicro(); }); ['board','voltage','resistor'].forEach(id => $(`#${id}`).addEventListener('input', compileMicro)); $('#copyCode').onclick = () => navigator.clipboard.writeText($('#codeOut').textContent); compileMicro(); }
function compileMicro() { const board = $('#board').value, parts = $$('.chip.active').map(x => x.dataset.part); const pins = board === 'ESP32' ? { LED: 'GPIO 18', Potentiometer: 'GPIO 34', 'Temperature Sensor': 'GPIO 35', 'Micro Servo Motor': 'GPIO 19' } : { LED: 'Pin 9', Potentiometer: 'A0', 'Temperature Sensor': 'A1', 'Micro Servo Motor': 'Pin 10' }; $('#wiring').textContent = parts.map(p => `${p}: Connect signal to ${pins[p]}, VCC to regulated 5V/3V3, GND to common ground.${p === 'LED' ? ` LED Anode to ${pins[p]}, Cathode via 220Ω resistor to GND.` : ''}`).join('\n') || 'Select peripherals to generate wiring.'; const v = +$('#voltage').value, r = +$('#resistor').value, ma = (v / r) * 1000; $('#ohm').innerHTML = `V=${v.toFixed(1)}V · R=${r}Ω · I=${ma.toFixed(1)}mA ` + (ma > 20 ? '<span class="danger">Unsafe for LED pin &gt;20mA</span>' : '<span class="warning">Within typical LED threshold</span>'); $('#codeOut').textContent = board === 'ESP32' ? micropython(parts, pins) : arduino(parts, pins); }
function arduino(parts, pins) { return `#include <Servo.h>\nServo servo;\nvoid setup(){\n  Serial.begin(9600);\n${parts.includes('LED') ? '  pinMode(9, OUTPUT);\n' : ''}${parts.includes('Micro Servo Motor') ? '  servo.attach(10);\n' : ''}}\nvoid loop(){\n${parts.includes('LED') ? '  analogWrite(9, 180);\n' : ''}${parts.includes('Potentiometer') ? '  int pot = analogRead(A0); Serial.println(pot);\n' : ''}${parts.includes('Temperature Sensor') ? '  int tempRaw = analogRead(A1); Serial.println(tempRaw * 0.488);\n' : ''}${parts.includes('Micro Servo Motor') ? '  servo.write(90);\n' : ''}  delay(250);\n}`; }
function micropython(parts, pins) { return `from machine import Pin, ADC, PWM\nfrom time import sleep\n${parts.includes('LED') ? 'led = PWM(Pin(18), freq=1000)\n' : ''}${parts.includes('Potentiometer') ? 'pot = ADC(Pin(34))\n' : ''}${parts.includes('Temperature Sensor') ? 'temp = ADC(Pin(35))\n' : ''}${parts.includes('Micro Servo Motor') ? 'servo = PWM(Pin(19), freq=50)\n' : ''}while True:\n${parts.includes('LED') ? '    led.duty(700)\n' : ''}${parts.includes('Potentiometer') ? '    print(pot.read())\n' : ''}${parts.includes('Temperature Sensor') ? '    print(temp.read())\n' : ''}${parts.includes('Micro Servo Motor') ? '    servo.duty(77)\n' : ''}    sleep(.25)`; }

function renderJarvis() { return `<div class="panel"><div id="chatFeed" class="log-feed chat-feed"><p class="chat-row"><strong>Jarvis</strong> Terminal ready. Try /time, /note text, or /clear.</p></div><form id="chatForm"><input id="chatInput" placeholder="Enter command or message..."></form></div>`; }
function bindJarvis() { $('#chatForm').onsubmit = e => { e.preventDefault(); const v = $('#chatInput').value.trim(); if (!v) return; $('#chatInput').value = ''; if (v === '/clear') return $('#chatFeed').innerHTML = ''; if (v === '/time') return chat('OS', new Date().toString()); if (v.startsWith('/note ')) { state.notes.push(v.slice(6)); return chat('Storage', `Saved note #${state.notes.length}: ${v.slice(6)}`); } chat('Jarvis', `Command received: ${v}`); }; }
function chat(who, msg) { $('#chatFeed').insertAdjacentHTML('beforeend', `<p class="chat-row"><strong>${who}</strong> ${msg}</p>`); $('#chatFeed').scrollTop = $('#chatFeed').scrollHeight; }
function bindApp(key) { ({ stocks: bindStocks, transcoder: bindTranscoder, micro: bindMicro, jarvis: bindJarvis }[key] || (() => {}))(); }

document.addEventListener('click', e => { if (e.target.matches('[data-next-stage]')) showStage(+e.target.dataset.nextStage); if (e.target.matches('[data-device]')) { state.device = e.target.dataset.device; $('#deviceLabel').textContent = `${state.device} profile`; showStage(2); } });
$('#closeSheet').onclick = closeActiveSheet; $('#navHome').onclick = closeActiveSheet; $('#navStacks').onclick = () => { renderTaskSwitcher(); $('#taskSwitcher').classList.toggle('open'); }; $('#navBack').onclick = () => state.activeApp ? closeActiveSheet() : showStage(Math.max(0, state.stage - 1));
renderLauncher();
